### ISSUE TITLE
Remove invalid path in xcodeproj  that points high scores file

### ISSUE THREAD

**Issue by BrainFeverMedia** [JonoFrench/Asteroids#1]
I got this error:

/Users/jonathanfrench/Projects/Asteroids/Asteroids/HiScores/HighScores.xcdatamodeld:: error: Could not fetch generated file paths: No current version for model at path /Users/jonathanfrench/Projects/Asteroids/Asteroids/HiScores/

Removing this invalid path from the xcodeproj file fixed error and it works!

**Comment by JonoFrench** [comment]
Cheers. Fixed it by removing the path in project file too. Change committed. Thx
